export const enum Network {
  SIFCHAIN = "sifchain",
  ETHEREUM = "ethereum",
  // The rest... sort by name
  AKASH = "akash",
  BAND = "band",
  COSMOSHUB = "cosmoshub",
  CRYPTO_ORG = "crypto-org",
  IRIS = "iris",
  IXO = "ixo",
  JUNO = "juno",
  LIKECOIN = "likecoin",
  OSMOSIS = "osmosis",
  PERSISTENCE = "persistence",
  REGEN = "regen",
  SENTINEL = "sentinel",
  TERRA = "terra",
  EMONEY = "emoney",
  EVMOS = "evmos",
  STARNAME = "starname",
  BITSONG = "bitsong",
  CERBERUS = "cerberus",
  COMDEX = "comdex",
  CHIHUAHUA = "chihuahua",
  KI = "ki",
  STARGAZE = "stargaze",
  SECRET = "secret",
}
