import { Network } from "entities";

export default {
  assets: [
    {
      symbol: "rowan",
      decimals: 18,
      name: "Rowan",
      imageUrl: "./images/siflogo.png",
      network: Network.SIFCHAIN,
      displaySymbol: "rowan",
      homeNetwork: Network.SIFCHAIN,
    },
    {
      decimals: 6,
      imageUrl:
        "https://assets.coingecko.com/coins/images/325/thumb/Tether-logo.png?1598003707",
      name: "Tether USDT",
      network: Network.SIFCHAIN,
      symbol: "cusdt",
      displaySymbol: "usdt",
      homeNetwork: Network.ETHEREUM,
    },
    {
      decimals: 18,
      imageUrl:
        "https://assets.coingecko.com/coins/images/279/small/ethereum.png?1595348880",
      name: "Ethereum",
      network: Network.SIFCHAIN,
      symbol: "ceth",
      displaySymbol: "eth",
      homeNetwork: Network.ETHEREUM,
    },
    {
      decimals: 18,
      imageUrl:
        "https://assets.coingecko.com/coins/images/677/thumb/basic-attention-token.png?1547034427",
      name: "Basic Attention Token",
      network: Network.SIFCHAIN,
      symbol: "cbat",
      displaySymbol: "bat",
      homeNetwork: Network.ETHEREUM,
    },
    {
      decimals: 18,
      imageUrl:
        "https://assets.coingecko.com/coins/images/681/thumb/JelZ58cv_400x400.png?1601449653",
      name: "Aragon",
      network: Network.SIFCHAIN,
      symbol: "cant",
      displaySymbol: "ant",
      homeNetwork: Network.ETHEREUM,
    },
    {
      decimals: 18,
      imageUrl:
        "https://assets.coingecko.com/coins/images/736/thumb/bancor.png?1547034477",
      name: "Bancor Network Token",
      network: Network.SIFCHAIN,
      symbol: "cbnt",
      displaySymbol: "bnt",
      homeNetwork: Network.ETHEREUM,
    },
    {
      decimals: 18,
      imageUrl:
        "https://assets.coingecko.com/coins/images/863/thumb/0x.png?1547034672",
      name: "0x",
      network: Network.SIFCHAIN,
      symbol: "czrx",
      displaySymbol: "zrx",
      homeNetwork: Network.ETHEREUM,
    },
    {
      decimals: 18,
      imageUrl:
        "https://assets.coingecko.com/coins/images/877/thumb/chainlink-new-logo.png?1547034700",
      name: "Chainlink",
      network: Network.SIFCHAIN,
      symbol: "clink",
      displaySymbol: "link",
      homeNetwork: Network.ETHEREUM,
    },
    {
      decimals: 18,
      imageUrl:
        "https://assets.coingecko.com/coins/images/878/thumb/decentraland-mana.png?1550108745",
      name: "Decentraland",
      network: Network.SIFCHAIN,
      symbol: "cmana",
      displaySymbol: "mana",
      homeNetwork: Network.ETHEREUM,
    },
    {
      decimals: 18,
      imageUrl:
        "https://assets.coingecko.com/coins/images/913/thumb/LRC.png?1572852344",
      name: "Loopring",
      network: Network.SIFCHAIN,
      symbol: "clrc",
      displaySymbol: "lrc",
      homeNetwork: Network.ETHEREUM,
    },
    {
      decimals: 18,
      imageUrl:
        "https://assets.coingecko.com/coins/images/1102/thumb/enjin-coin-logo.png?1547035078",
      name: "Enjin Coin",
      network: Network.SIFCHAIN,
      symbol: "cenj",
      displaySymbol: "enj",
      homeNetwork: Network.ETHEREUM,
    },
    {
      decimals: 18,
      imageUrl:
        "https://assets.coingecko.com/coins/images/3406/thumb/SNX.png?1598631139",
      name: "Synthetix Network Token",
      network: Network.SIFCHAIN,
      symbol: "csnx",
      displaySymbol: "snx",
      homeNetwork: Network.ETHEREUM,
    },
    {
      decimals: 18,
      imageUrl:
        "https://assets.coingecko.com/coins/images/3449/thumb/TUSD.png?1559172762",
      name: "TrueUSD",
      network: Network.SIFCHAIN,
      symbol: "ctusd",
      displaySymbol: "tusd",
      homeNetwork: Network.ETHEREUM,
    },
    {
      decimals: 18,
      imageUrl:
        "https://assets.coingecko.com/coins/images/3687/thumb/ocean-protocol-logo.jpg?1547038686",
      name: "Ocean Protocol",
      network: Network.SIFCHAIN,
      symbol: "cocean",
      displaySymbol: "ocean",
      homeNetwork: Network.ETHEREUM,
    },
    {
      decimals: 18,
      imageUrl:
        "https://assets.coingecko.com/coins/images/4001/thumb/Fantom.png?1558015016",
      name: "Fantom",
      network: Network.SIFCHAIN,
      symbol: "cftm",
      displaySymbol: "ftm",
      homeNetwork: Network.ETHEREUM,
    },
    {
      decimals: 18,
      imageUrl:
        "https://assets.coingecko.com/coins/images/5013/thumb/sUSD.png?1562212426",
      name: "sUSD",
      network: Network.SIFCHAIN,
      symbol: "csusd",
      displaySymbol: "susd",
      homeNetwork: Network.ETHEREUM,
    },
    {
      decimals: 6,
      imageUrl:
        "https://assets.coingecko.com/coins/images/6319/thumb/USD_Coin_icon.png?1547042389",
      name: "USD Coin",
      network: Network.SIFCHAIN,
      symbol: "cusdc",
      displaySymbol: "usdc",
      homeNetwork: Network.ETHEREUM,
    },
    {
      decimals: 8,
      imageUrl:
        "https://assets.coingecko.com/coins/images/7310/thumb/cypto.png?1547043960",
      name: "Crypto com Coin",
      network: Network.SIFCHAIN,
      symbol: "ccro",
      displaySymbol: "CRO (ERC-20)",
      homeNetwork: Network.ETHEREUM,
      decommissioned: true,
      decommissionReason:
        "Crypto.org's ERC-20 token has been decommissioned on Sifchain in favor of the Cosmos CRO token. Please export all CRO (ERC-20) off of Sifchain.",
    },
    {
      decimals: 8,
      imageUrl:
        "https://assets.coingecko.com/coins/images/7598/thumb/wrapped_bitcoin_wbtc.png?1548822744",
      name: "Wrapped Bitcoin",
      network: Network.SIFCHAIN,
      symbol: "cwbtc",
      displaySymbol: "wbtc",
      homeNetwork: Network.ETHEREUM,
    },
    {
      decimals: 18,
      imageUrl:
        "https://assets.coingecko.com/coins/images/9368/thumb/swipe.png?1566792311",
      name: "Swipe",
      network: Network.SIFCHAIN,
      symbol: "csxp",
      displaySymbol: "sxp",
      homeNetwork: Network.ETHEREUM,
    },
    {
      decimals: 18,
      imageUrl:
        "https://assets.coingecko.com/coins/images/9545/thumb/band-protocol.png?1568730326",
      name: "Band Protocol",
      network: Network.SIFCHAIN,
      symbol: "cband",
      displaySymbol: "band",
      homeNetwork: Network.ETHEREUM,
    },
    {
      decimals: 18,
      imageUrl:
        "https://assets.coingecko.com/coins/images/9956/thumb/dai-multi-collateral-mcd.png?1574218774",
      name: "Dai Stablecoin",
      network: Network.SIFCHAIN,
      symbol: "cdai",
      displaySymbol: "dai",
      homeNetwork: Network.ETHEREUM,
    },
    {
      decimals: 18,
      imageUrl:
        "https://assets.coingecko.com/coins/images/10775/thumb/COMP.png?1592625425",
      name: "Compound",
      network: Network.SIFCHAIN,
      symbol: "ccomp",
      displaySymbol: "comp",
      homeNetwork: Network.ETHEREUM,
    },
    {
      decimals: 18,
      imageUrl:
        "https://assets.coingecko.com/coins/images/10951/thumb/UMA.png?1586307916",
      name: "UMA",
      network: Network.SIFCHAIN,
      symbol: "cuma",
      displaySymbol: "uma",
      homeNetwork: Network.ETHEREUM,
    },
    {
      decimals: 18,
      imageUrl:
        "https://assets.coingecko.com/coins/images/11683/thumb/Balancer.png?1592792958",
      name: "Balancer",
      network: Network.SIFCHAIN,
      symbol: "cbal",
      displaySymbol: "bal",
      homeNetwork: Network.ETHEREUM,
    },
    {
      decimals: 18,
      imageUrl:
        "https://assets.coingecko.com/coins/images/11849/thumb/yfi-192x192.png?1598325330",
      name: "yearn finance",
      network: Network.SIFCHAIN,
      symbol: "cyfi",
      displaySymbol: "yfi",
      homeNetwork: Network.ETHEREUM,
    },
    {
      decimals: 6,
      imageUrl:
        "https://assets.coingecko.com/coins/images/11970/thumb/serum-logo.png?1597121577",
      name: "Serum",
      network: Network.SIFCHAIN,
      symbol: "csrm",
      displaySymbol: "srm",
      homeNetwork: Network.ETHEREUM,
    },
    {
      decimals: 18,
      imageUrl:
        "https://assets.coingecko.com/coins/images/11976/thumb/Cream.png?1596593418",
      name: "Cream",
      network: Network.SIFCHAIN,
      symbol: "ccream",
      displaySymbol: "cream",
      homeNetwork: Network.ETHEREUM,
    },
    {
      decimals: 18,
      imageUrl:
        "https://assets.coingecko.com/coins/images/12129/thumb/sandbox_logo.jpg?1597397942",
      name: "SAND",
      network: Network.SIFCHAIN,
      symbol: "csand",
      displaySymbol: "sand",
      homeNetwork: Network.ETHEREUM,
    },
    {
      decimals: 18,
      imageUrl:
        "https://assets.coingecko.com/coins/images/12271/thumb/512x512_Logo_no_chop.png?1606986688",
      name: "Sushi",
      network: Network.SIFCHAIN,
      symbol: "csushi",
      displaySymbol: "sushi",
      homeNetwork: Network.ETHEREUM,
    },
    {
      decimals: 18,
      imageUrl:
        "https://assets.coingecko.com/coins/images/12440/thumb/esd_logo_circle.png?1603676421",
      name: "Empty Set Dollar",
      network: Network.SIFCHAIN,
      symbol: "cesd",
      displaySymbol: "esd",
      homeNetwork: Network.ETHEREUM,
    },
    {
      decimals: 18,
      imageUrl:
        "https://assets.coingecko.com/coins/images/12504/thumb/uniswap-uni.png?1600306604",
      name: "Uniswap",
      network: Network.SIFCHAIN,
      symbol: "cuni",
      displaySymbol: "uni",
      homeNetwork: Network.ETHEREUM,
    },
    {
      decimals: 18,
      imageUrl:
        "https://assets.coingecko.com/coins/images/12645/thumb/AAVE.png?1601374110",
      name: "Aave",
      network: Network.SIFCHAIN,
      symbol: "caave",
      displaySymbol: "aave",
      homeNetwork: Network.ETHEREUM,
    },
    {
      decimals: 18,
      imageUrl:
        "https://assets.coingecko.com/coins/images/12811/thumb/barnbridge.jpg?1602728853",
      name: "BarnBridge",
      network: Network.SIFCHAIN,
      symbol: "cbond",
      displaySymbol: "bond",
      homeNetwork: Network.ETHEREUM,
    },
    {
      decimals: 18,
      imageUrl:
        "https://assets.coingecko.com/coins/images/13238/thumb/WFIL-Icon.png?1606630561",
      name: "Wrapped Filecoin",
      network: Network.SIFCHAIN,
      symbol: "cwfil",
      displaySymbol: "wfil",
      homeNetwork: Network.ETHEREUM,
    },
    {
      decimals: 18,
      imageUrl:
        "https://assets.coingecko.com/coins/images/13397/thumb/Graph_Token.png?1608145566",
      name: "The Graph",
      network: Network.SIFCHAIN,
      symbol: "cgrt",
      displaySymbol: "grt",
      homeNetwork: Network.ETHEREUM,
    },
    {
      decimals: 18,
      imageUrl:
        "https://assets.coingecko.com/coins/images/13454/thumb/lon_logo.png?1608701720",
      name: "Tokenlon",
      network: Network.SIFCHAIN,
      symbol: "clon",
      displaySymbol: "lon",
      homeNetwork: Network.ETHEREUM,
    },
    {
      decimals: 18,
      imageUrl:
        "https://assets.coingecko.com/coins/images/13469/thumb/1inch-token.png?1608803028",
      name: "1inch",
      network: Network.SIFCHAIN,
      symbol: "c1inch",
      displaySymbol: "1inch",
      homeNetwork: Network.ETHEREUM,
    },
    {
      decimals: 18,
      imageUrl:
        "https://assets.coingecko.com/coins/images/13677/thumb/BrMhBTr8_400x400.jpg?1610723303",
      name: "THORChain ERC20",
      network: Network.SIFCHAIN,
      symbol: "crune",
      displaySymbol: "rune",
      homeNetwork: Network.ETHEREUM,
    },
    {
      decimals: 6,
      imageUrl:
        "https://assets.coingecko.com/coins/images/13767/thumb/Secret_S_Black_Coingecko.png?1611667298",
      name: "Secret ERC20",
      network: Network.SIFCHAIN,
      symbol: "cwscrt",
      displaySymbol: "wscrt",
      homeNetwork: Network.ETHEREUM,
    },
    {
      decimals: 18,
      imageUrl:
        "https://assets.coingecko.com/coins/images/3334/small/iotex-logo.png?1547037941",
      name: "IoTeX",
      network: Network.SIFCHAIN,
      symbol: "ciotx",
      displaySymbol: "iotx",
      homeNetwork: Network.ETHEREUM,
    },
    {
      imageUrl:
        "https://assets.coingecko.com/coins/images/13504/small/Group_10572.png?1610534130",
      name: "Reef Finance",
      symbol: "creef",
      network: Network.SIFCHAIN,
      decimals: 18,
      displaySymbol: "reef",
      homeNetwork: Network.ETHEREUM,
    },
    {
      imageUrl:
        "https://assets.coingecko.com/coins/images/4932/thumb/_QPpjoUi_400x400.jpg?1566430520",
      name: "COCOS BCX",
      symbol: "ccocos",
      network: Network.SIFCHAIN,
      decimals: 18,
      displaySymbol: "cocos",
      homeNetwork: Network.ETHEREUM,
    },
    {
      decimals: 18,
      imageUrl:
        "https://assets.coingecko.com/coins/images/3373/small/IuNzUb5b_400x400.jpg?1589526336",
      name: "Keep Network",
      network: Network.SIFCHAIN,
      symbol: "ckeep",
      displaySymbol: "keep",
      homeNetwork: Network.ETHEREUM,
    },
    {
      decimals: 18,
      imageUrl:
        "https://assets.coingecko.com/coins/images/3296/small/op.jpg?1547037878",
      name: "Origin Protocol",
      network: Network.SIFCHAIN,
      symbol: "cogn",
      displaySymbol: "ogn",
      homeNetwork: Network.ETHEREUM,
    },
    {
      decimals: 18,
      imageUrl:
        "https://assets.coingecko.com/coins/images/12782/small/logocircle.png?1611944557",
      name: "DAOfi",
      network: Network.SIFCHAIN,
      symbol: "cdaofi",
      displaySymbol: "daofi",
      homeNetwork: Network.ETHEREUM,
    },
    {
      decimals: 18,
      imageUrl:
        "https://assets.coingecko.com/coins/images/12509/small/linear.jpg?1606884470",
      name: "Linear",
      network: Network.SIFCHAIN,
      symbol: "clina",
      displaySymbol: "lina",
      homeNetwork: Network.ETHEREUM,
    },
    {
      decimals: 18,
      imageUrl:
        "https://assets.coingecko.com/coins/images/9351/small/12ships.png?1566485390",
      name: "12Ships",
      network: Network.SIFCHAIN,
      symbol: "ctshp",
      displaySymbol: "tshp",
      homeNetwork: Network.ETHEREUM,
    },
    {
      decimals: 18,
      imageUrl:
        "https://assets.coingecko.com/coins/images/13803/small/b20.png?1611996305",
      name: "B.20",
      network: Network.SIFCHAIN,
      symbol: "cb20",
      displaySymbol: "b20",
      homeNetwork: Network.ETHEREUM,
    },
    {
      decimals: 18,
      imageUrl:
        "https://assets.coingecko.com/coins/images/3328/small/Akropolis.png?1547037929",
      name: "Akropolis",
      network: Network.SIFCHAIN,
      symbol: "cakro",
      displaySymbol: "akro",
      homeNetwork: Network.ETHEREUM,
    },
    {
      decimals: 18,
      imageUrl:
        "https://assets.coingecko.com/coins/images/12623/small/RFUEL_SQR.png?1602481093",
      name: "Rio Fuel Token",
      network: Network.SIFCHAIN,
      symbol: "crfuel",
      displaySymbol: "rfuel",
      homeNetwork: Network.ETHEREUM,
    },
    {
      decimals: 18,
      imageUrl:
        "https://assets.coingecko.com/coins/images/12843/small/image.png?1611212077",
      name: "Rally",
      network: Network.SIFCHAIN,
      symbol: "crly",
      displaySymbol: "rly",
      homeNetwork: Network.ETHEREUM,
    },
    {
      decimals: 18,
      imageUrl: "https://etherscan.io/token/images/convergence_32.png",
      name: "Convergence",
      network: Network.SIFCHAIN,
      symbol: "cconv",
      displaySymbol: "conv",
      homeNetwork: Network.ETHEREUM,
    },
    {
      decimals: 18,
      imageUrl: "https://etherscan.io/token/images/render_32.png",
      name: "Render Token",
      network: Network.SIFCHAIN,
      symbol: "crndr",
      displaySymbol: "rndr",
      homeNetwork: Network.ETHEREUM,
    },
    {
      decimals: 18,
      imageUrl: "https://etherscan.io/token/images/paidnetwork_32.png",
      name: "PAID Network",
      network: Network.SIFCHAIN,
      symbol: "cpaid",
      displaySymbol: "paid",
      homeNetwork: Network.ETHEREUM,
    },
    {
      decimals: 18,
      imageUrl:
        "https://assets.coingecko.com/coins/images/14460/small/Tidal-mono.png?1616233894",
      name: "Tidal",
      network: Network.SIFCHAIN,
      symbol: "ctidal",
      displaySymbol: "tidal",
      homeNetwork: Network.ETHEREUM,
    },
    {
      decimals: 18,
      imageUrl:
        "https://assets.coingecko.com/coins/images/11939/small/SHIBLOGO.png?1600752116",
      name: "SHIBA INU",
      network: Network.SIFCHAIN,
      symbol: "cshib",
      displaySymbol: "shib",
      homeNetwork: Network.ETHEREUM,
    },
    {
      decimals: 18,
      imageUrl: "https://etherscan.io/token/images/dogekiller_32.png",
      name: "DOGE KILLER",
      network: Network.SIFCHAIN,
      symbol: "cleash",
      displaySymbol: "leash",
      homeNetwork: Network.ETHEREUM,
    },
    {
      symbol: "uatom",
      decimals: 6,
      name: "Atom",
      network: Network.SIFCHAIN,
      label: "Atom",
      imageUrl:
        "https://assets.coingecko.com/coins/images/1481/small/cosmos_hub.png?1555657960",
      displaySymbol: "atom",
      homeNetwork: Network.COSMOSHUB,
    },
    {
      symbol: "uakt",
      decimals: 6,
      name: "Akash Token",
      network: Network.SIFCHAIN,
      label: "AKT",
      imageUrl:
        "https://assets.coingecko.com/coins/images/12785/small/akash-logo.png?1615447676",
      displaySymbol: "akt",
      homeNetwork: Network.AKASH,
    },
    {
      symbol: "udvpn",
      decimals: 6,
      name: "Sentinel",
      network: Network.SIFCHAIN,
      label: "Sentinel",
      imageUrl:
        "https://assets.coingecko.com/coins/images/14879/small/Sentinel_512X512.png?1622174499",
      displaySymbol: "dvpn",
      homeNetwork: Network.SENTINEL,
    },
    {
      symbol: "uiris",
      decimals: 6,
      name: "IRIS",
      network: Network.SIFCHAIN,
      label: "IRIS",
      imageUrl:
        "https://assets.coingecko.com/coins/images/5135/small/IRIS.png?1557999365",
      displaySymbol: "iris",
      homeNetwork: Network.IRIS,
    },
    {
      symbol: "basecro",
      displaySymbol: "cro",
      decimals: 8,
      name: "CRO",
      network: Network.SIFCHAIN,
      label: "CRO",
      imageUrl:
        "https://assets.coingecko.com/coins/images/7310/small/cypto.png?1547043960",
      homeNetwork: Network.CRYPTO_ORG,
      decommissioned: true,
    },
    {
      symbol: "uxprt",
      displaySymbol: "xprt",
      decimals: 6,
      name: "xprt",
      network: Network.SIFCHAIN,
      label: "xprt",
      imageUrl: "https://persistence.one/favicon.png",
      homeNetwork: Network.PERSISTENCE,
    },
    {
      symbol: "uregen",
      displaySymbol: "regen",
      decimals: 6,
      name: "regen",
      network: Network.SIFCHAIN,
      label: "regen",
      imageUrl:
        "https://assets.coingecko.com/coins/images/16733/small/REGEN.png?1624861317",
      homeNetwork: Network.REGEN,
      decommissioned: true,
    },
  ],
};
