name: "Frontend: Docker: Build"

on:
  push:
    branches:
      - "master"

jobs:
  test_build_push:
    runs-on: ubuntu-latest
    env:
      image: "sifchain/frontend"

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: yarn

      - name: Set env vars
        shell: bash
        run: |
          set +x
          BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})
          TAG_NAME=$(git tag --points-at HEAD)
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          echo "VITE_APP_VERSION=$(cat ./app/package.json | jq '.version' | tr -d '"')" >> $GITHUB_ENV
          echo "VITE_APP_SHA=$GITHUB_SHA" >> $GITHUB_ENV
          if [[ $BRANCH_NAME == 'master' ]]
          then
            echo "SUBDOMAIN=staging" >> $GITHUB_ENV
            echo "VITE_APP_DEPLOYMENT=production" >> $GITHUB_ENV
          elif [[ "$TAG_NAME" != '' ]]
          then
            echo "SUBDOMAIN=testnet" >> $GITHUB_ENV
            echo "VITE_APP_DEPLOYMENT=staging" >> $GITHUB_ENV
          else
            echo "SUBDOMAIN=devnet" >> $GITHUB_ENV
            echo "VITE_APP_DEPLOYMENT=develop" >> $GITHUB_ENV
          fi
          echo $(cat $GITHUB_ENV)

      - name: "Install Dependencies & Build Frontend Application"
        run: |
          set +x
          cd app/
          yarn
          yarn build

      - name: "Build & Push Docker Image"
        shell: bash
        env:
          DOCKER_USERNAME: "${{ secrets.DOCKER_USERNAME }}"
          DOCKER_PASSWORD: "${{ secrets.DOCKER_PASSWORD }}"
        run: |
          set +x
          mv Dockerfile.staticonly Dockerfile
          docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
          if [ -z "${TAG_NAME}" ]; then
            TAG_NAME=$(cat app/package.json | jq .version | sed 's/"//g')
          fi
          docker build -t ${image}:${TAG_NAME} .
          docker push ${image}:${TAG_NAME}
